stages:
  - validate
  - lint
  - test

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:0.12.8"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - terraform init
    - terraform validate
  artifacts:
    paths:
      - .terraform
      
terralint:
  stage: lint
  image:
    name: "wata727/tflint"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint

terratest:
  stage: test
  image:
    name: "hashicorp/terraform:full"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - export GOOGLE_CLOUD_PROJECT=YOUR_PROJECT
    - testdir=$(pwd)/test
    - cd $testdir
    - apk add --no-cache gcc libc-dev bind-tools
    - go test -v gcp_gcs_test.go
